# This is the CI configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
atk = {}
audiod = {}
autoconf = {}
automake = {}
#bash = {} # setrlimit
binutils = {}
bootloader = {}
ca-certificates = {}
cairo = {}
cairodemo = {}
#cargo = {} # curl-config not found
cleye = {}
cmatrix = {}
contain = {}
coreutils = {}
cpal = {}
curl = {}
#dash = {} # setrlimit
diffutils = {}
dosbox = {}
drivers = {}
#drivers-041 = {}
#duktape = {} # strptime
eduke32 = {}
exampled = {}
expat = {}
extrautils = {}
#fd = {} # ctrlc-3.1.1
ffmpeg = {}
findutils = {}
fontconfig = {}
#freeciv = {}
freedoom = {}
#freeglut = {}
freetype = {}
#friar = {} # mio patch
fribidi = {}
#game-2048 = {} # rustc-serialize
games = {}
#gawk = {} # langinfo.h
gcc = {}
gdbserver = {}
#gdk-pixbuf = {} # shared-mime-info
gears = {}
generaluser-gs = {}
gettext = {}
gigalomania = {}
git = {}
glib = {}
glium = {}
glutin = {}
gnu-binutils = {}
gnu-grep = {}
gnu-make = {}
#gstreamer = {} # conflict with thread local errno
harfbuzz = {}
#hematite = {} # needs crate patches for redox-unix
init = {}
installer = {}
ion = {}
ipcd = {}
jansson = {}
kernel = {}
keyboard-sfx = {}
lci = {}
libc-bench = {}
libffi = {}
libiconv = {}
libjpeg = {}
libogg = {}
liborbital = {}
libpng = {}
libsodium = {}
libvorbis = {}
libxml2 = {}
llvm = {}
logd = {}
#lua = {} # tmpnam
#mdp = {} # ncursesw
mesa = {}
mesa_glu = {}
#mgba = {} # no longer builds binary
#miniserve = {} # actix
nasm = {}
#ncdu = {} # fails to link with ncurses
ncurses = {}
#ncursesw = {} # mkstemp configure hang
netdb = {}
netstack = {}
netsurf = {}
netutils = {}
#neverball = {} # error finding SDL includes
#newlib = {} # obsolete
#newlibtest = {} # obsolete
nghttp2 = {}
nulld = {}
openjazz = {}
openssl = {}
openttd = {}
openttd-opengfx = {}
openttd-openmsx = {}
openttd-opensfx = {}
orbclient = {}
orbdata = {}
orbital = {}
orbterm = {}
orbutils = {}
orbutils-background = {}
orbutils-launcher = {}
orbutils-orblogin = {}
osdemo = {}
pango = {}
#pastel = {} # needs crate patches for redox-unix
patch = {}
#pathfinder = {} # servo-fontconfig
#pciids = {}
pcre = {}
periodictable = {}
#perl = {} # ctermid, tempnam, ttyname
pixelcannon = {}
pixman = {}
pkg-config = {}
pkgutils = {}
#powerline = {} # dirs
prboom = {}
ptyd = {}
#python = {} # getaddrinfo
#qemu = {}
randd = {}
readline = {}
redoxerd = {}
redoxfs = {}
#redox-fatfs = {}
#redox-ssh = {}
relibc = {}
#relibc-tests = {}
ripgrep = {}
rodioplay = {}
rs-nes = {}
#rust = {}
rust64 = {}
rust-cairo = {}
rust-cairo-demo = {}
rustual-boy = {}
schismtracker = {}
scummvm = {}
sdl = {}
sdl2 = {}
sdl2_gears = {}
sdl2_image = {}
sdl2_mixer = {}
sdl2_ttf = {}
sdl_gfx = {}
sdl_image = {}
sdl_mixer = {}
sdl-player = {}
#sdl_ttf = {} # configure patch needs to be updated
sed = {}
#servo = {} # some more crates to port
#shared-mime-info = {} # intltool-update out of date
shellstorm = {}
smith = {}
sodium = {}
sopwith = {}
#ssh = {}
strace = {}
#syobonaction = {} # sdl_ttf errors
terminfo = {}
#termplay = {} # backtrace cannot find link.h
timidity = {}
ttf-hack = {}
userutils = {}
uutils = {}
vice = {}
#vim = {} # stack_t not matching
vttest = {}
#webrender = {} # unwind
winit = {}
xz = {}
zerod = {}
zlib = {}
